import { parseIntent, type Intent } from "./cdui/intent";

import { allProjects } from "./cdui/projects";
import { projectListFromProjects } from "./cdui/types";


import React, { useState } from "react";
import "./App.css";

import { ScreenRenderer } from "./cdui/components/ScreenRenderer";
import type { ScreenDescription } from "./cdui/types";

/**
 * Some sample screens so we can switch between them based on commands.
 * Later these will be generated by AI.
 */

const homeScreen: ScreenDescription = {
  screenId: "home",
  layout: "column",
  widgets: [
    {
      type: "text",
      variant: "h1",
      content: "Welcome to the Conversational Portfolio (CDUI demo)",
    },
    projectListFromProjects(allProjects),
    {
      type: "button_row",
      buttons: [{ id: "talk_to_interface", label: "Talk to the interface" }],
    },
  ],
};


const javaScreen: ScreenDescription = {
  screenId: "java_projects",
  layout: "column",
  widgets: [
    {
      type: "text",
      variant: "h1",
      content: "Java-focused projects",
    },
    projectListFromProjects(
      allProjects.filter((p) => p.techStack.includes("Java"))
    ),
    {
      type: "button_row",
      buttons: [{ id: "talk_to_interface", label: "Ask for something else" }],
    },
  ],
};


const backendScreen: ScreenDescription = {
  screenId: "backend_projects",
  layout: "column",
  widgets: [
    {
      type: "text",
      variant: "h1",
      content: "Backend-oriented projects",
    },
    projectListFromProjects(
      allProjects.filter(
        (p) =>
          p.kind === "backend" ||
          p.kind === "fullstack" ||
          p.kind === "cli"
      )
    ),
    {
      type: "button_row",
      buttons: [{ id: "talk_to_interface", label: "Refine the view" }],
    },
  ],
};


const cvScreen: ScreenDescription = {
  screenId: "cv_download",
  layout: "column",
  widgets: [
    {
      type: "text",
      variant: "h1",
      content: "CV download",
    },
    {
      type: "text",
      variant: "body",
      content:
        "In the final version, a real CV PDF will be generated here on demand.",
    },
    {
      type: "button_row",
      buttons: [
        { id: "download_cv", label: "Download CV (mock)" },
        { id: "talk_to_interface", label: "Ask something else" },
      ],
    },
  ],
};

type Mode = "ui" | "chat";

function App() {
  const [mode, setMode] = useState<Mode>("ui");
  const [history, setHistory] = useState<ScreenDescription[]>([homeScreen]);
  const currentScreen = history[history.length - 1];


  const [chatInput, setChatInput] = useState("");
  const [systemPrompt, setSystemPrompt] = useState(
    "You are not browsing pages. You are shaping the interface. What do you want to see?"
  );

  /**
   * Handle button clicks from the CDUI screen.
   * For now there's only one special button: "talk_to_interface".
   */
  const handleAction = (actionId: string) => {
    if (actionId === "talk_to_interface") {
      // Switch into full-screen chat mode
      setMode("chat");
      return;
    }

    if (actionId === "download_cv") {
      // Mock CV download
      alert("This will trigger a real CV download in a later version.");
      return;
    }

    // Later: other action IDs will be handled here.
    console.log("Unhandled action:", actionId);
  };

  /**
   * Decide which screen to show based on the user's text command.
   * This is our "mock AI" for now.
   */
 const handleCommand = (text: string) => {
  const intent: Intent = parseIntent(text);

  switch (intent.type) {
    case "SHOW_CV": {
      setHistory((prev) => [...prev, cvScreen]);
      setSystemPrompt("CV section opened. You can request other views anytime.");
      setMode("ui");
      setChatInput("");
      return;
    }

    case "SHOW_PROJECTS": {
      let nextScreen: ScreenDescription = homeScreen;

      if (intent.tech === "java") {
        nextScreen = javaScreen;
      } else if (intent.tech === "backend" || intent.tech === "firebase") {
        // For now backend + firebase both go to backendScreen
        nextScreen = backendScreen;
      }

      setHistory((prev) => [...prev, nextScreen]);
      setSystemPrompt("View updated. You can refine it again.");
      setMode("ui");
      setChatInput("");
      return;
    }

    case "GO_BACK": {
      setHistory((prev) => {
        if (prev.length <= 1) return prev; // already at root
        const copy = [...prev];
        copy.pop();
        return copy;
      });
      setSystemPrompt("Went back to the previous view.");
      setMode("ui");
      setChatInput("");
      return;
    }

    case "SHOW_ANY_PROJECTS": {
      // for now, treat this as backendScreen or rotate between screens later
      setHistory((prev) => [...prev, backendScreen]);
      setSystemPrompt("Here is another example from the portfolio.");
      setMode("ui");
      setChatInput("");
      return;
    }    

    case "UNKNOWN":
    default: {
      setSystemPrompt(
        "I'm not sure what you mean. Try phrases like 'java projects', 'backend projects', 'firebase projects', 'cv', or 'go back'."
      );
      return;
    }
  }
};


  const handleChatSubmit: React.FormEventHandler<HTMLFormElement> = (e) => {
    e.preventDefault();
    handleCommand(chatInput);
  };

  // MODE: CHAT (full-screen)
  if (mode === "chat") {
    return (
      <div className="chat-fullscreen">
        <div className="chat-box">
          <p className="chat-label">Interface</p>
          <p className="chat-system">{systemPrompt}</p>

          <form onSubmit={handleChatSubmit} className="chat-form">
            <input
              className="chat-input"
              placeholder="Type what you want the interface to become..."
              value={chatInput}
              onChange={(e) => setChatInput(e.target.value)}
              autoFocus
            />
            <div className="chat-buttons">
              <button type="submit">Commit change</button>
              <button
                type="button"
                onClick={() => {
                  setChatInput("");
                  setMode("ui");
                }}
              >
                Cancel
              </button>
            </div>
          </form>
        </div>
      </div>
    );
  }

  // MODE: UI (full-screen CDUI screen)
  return (
    <div className="ui-fullscreen">
      <ScreenRenderer screen={currentScreen} onAction={handleAction} />
    </div>
  );
}

export default App;
